import { useEffect, useState, useCallback } from 'react'; import { Link } from 'react-router-dom';
import { api, token, setToken, toast } from '../api'; import { Counter, Loading, Err, Sev, Stat } from '../components'; import { STATUSES, SEVERITIES, CATEGORIES } from '../constants';
function Login({ done }) {
  const [em, setEm] = useState(''), [pw, setPw] = useState(''), [err, setErr] = useState(''), [busy, setBusy] = useState(false);
  const go = async ev => { ev.preventDefault(); setBusy(true); setErr(''); try { const r = await api('/auth/login', { method: 'POST', body: { email: em, password: pw } }); setToken(r.token); toast('Welcome, ' + r.user.name); done(); } catch (x) { setErr(x.message); } finally { setBusy(false); } };
  return <form className="card narrow" onSubmit={go}><h2>Admin Login</h2><label>Email</label><input type="email" value={em} onChange={e => setEm(e.target.value)} required /><label>Password</label><input type="password" value={pw} onChange={e => setPw(e.target.value)} required />{err && <div className="sm" style={{ color: 'var(--rd)' }}>{err}</div>}<button className="btn" disabled={busy} style={{ width: '100%' }}>{busy ? 'Signing in…' : 'Sign in'}</button><div className="sm mu" style={{ marginTop: 8 }}>Credentials come from the backend .env.</div></form>;
}
const Bars = ({ title, keys, data, total }) => <div className="card"><b>{title}</b>{keys.map(k => <div key={k} className="sm" style={{ margin: '8px 0' }}>{k} <span className="mu">({data[k] || 0})</span><div className="bar"><i style={{ '--w': (total ? (data[k] || 0) / total * 100 : 0) + '%' }} /></div></div>)}</div>;
function Dash({ out }) {
  const [a, setA] = useState(null), [l, setL] = useState(null), [e, setE] = useState(''), [f, setF] = useState({ search: '', severity: '', status: '', category: '', sort: '-createdAt', page: 1 });
  const loadA = useCallback(() => api('/analytics').then(setA).catch(x => { setE(x.message); if (x.status === 401) out(); }), [out]); useEffect(() => { loadA(); }, [loadA]);
  useEffect(() => { const t = setTimeout(() => { const p = new URLSearchParams({ limit: 8, ...Object.fromEntries(Object.entries(f).filter(([, v]) => v !== '')) }); api('/issues?' + p).then(setL).catch(x => setE(x.message)); }, 250); return () => clearTimeout(t); }, [f]);
  const set = (k, v) => setF(o => ({ ...o, [k]: v, page: k === 'page' ? v : 1 }));
  if (e) return <Err msg={e} retry={() => { setE(''); loadA(); }} />; if (!a || !l) return <Loading />;
  return <><div className="row" style={{ justifyContent: 'space-between' }}><h2>CivicAI <span className="g">Command Center</span></h2><button className="btn s" onClick={out}>Logout</button></div>
    <div className="sm mu" style={{ marginBottom: 12 }}>All figures are computed from database records.</div>
    <div className="grid c4">{[['Total Issues', a.total], ['Open', a.open], ['High/Critical Open', a.highOrCriticalOpen], ['Resolved', a.resolved]].map(([t, n]) => <div className="card" key={t}>{t}<div className="big"><Counter to={n} /></div></div>)}</div>
    {a.total === 0 ? <div className="card empty" style={{ marginTop: 16 }}>No reports yet</div> : <div className="grid c3" style={{ marginTop: 16 }}><Bars title="By Category" keys={CATEGORIES.filter(c => a.byCategory[c])} data={a.byCategory} total={a.total} /><Bars title="By Severity" keys={SEVERITIES} data={a.bySeverity} total={a.total} /><Bars title="By Status" keys={STATUSES} data={a.byStatus} total={a.total} /></div>}
    <div className="card" style={{ marginTop: 16 }}><b>Issues over last 30 days</b><div className="trend">{a.trend.length ? a.trend.map(t => <div key={t.date} title={`${t.date}: ${t.count}`} style={{ height: 14 + t.count * 18 }} />) : <span className="mu sm">No data</span>}</div></div>
    <div className="card" style={{ marginTop: 16 }}><div className="grid c5"><input placeholder="Search…" value={f.search} onChange={e => set('search', e.target.value)} />
      <select value={f.severity} onChange={e => set('severity', e.target.value)}><option value="">Severity</option>{SEVERITIES.map(s => <option key={s}>{s}</option>)}</select>
      <select value={f.category} onChange={e => set('category', e.target.value)}><option value="">Category</option>{CATEGORIES.map(s => <option key={s}>{s}</option>)}</select>
      <select value={f.status} onChange={e => set('status', e.target.value)}><option value="">Status</option>{STATUSES.map(s => <option key={s}>{s}</option>)}</select>
      <select value={f.sort} onChange={e => set('sort', e.target.value)}><option value="-createdAt">Newest</option><option value="createdAt">Oldest</option><option value="-supportCount">Most reports</option></select></div>
      <div style={{ overflowX: 'auto' }}>{l.items.length ? <table><thead><tr><th>ID</th><th>Issue</th><th>Category</th><th>Severity</th><th>Dept</th><th>Reports</th><th>Status</th><th>Created</th><th /></tr></thead><tbody>{l.items.map(i => <tr key={i._id}><td>{i.issueId}</td><td>{i.issueType}</td><td>{i.category}</td><td><Sev v={i.severity} /></td><td>{i.suggestedDepartment}</td><td>{i.supportCount}</td><td><Stat v={i.status} /></td><td>{new Date(i.createdAt).toLocaleDateString()}</td><td><Link className="btn s" to={`/issue/${i.issueId}`}>Open</Link></td></tr>)}</tbody></table> : <div className="empty">No reports match</div>}</div>
      <div className="row" style={{ justifyContent: 'center' }}><button className="btn s" disabled={l.page <= 1} onClick={() => set('page', l.page - 1)}>‹</button><span className="sm">{l.page} / {l.pages}</span><button className="btn s" disabled={l.page >= l.pages} onClick={() => set('page', l.page + 1)}>›</button></div></div></>;
}
export default function Admin() { const [t, setT] = useState(token()); const out = useCallback(() => { setToken(null); setT(null); }, []); return t ? <Dash out={out} /> : <Login done={() => setT(token())} />; }
